### ISSUE TITLE
2 mistakes in documentation

### ISSUE THREAD

**Issue by akarelas** [jberger/Minion-Notifier#2]
Look at https://metacpan.org/pod/Minion::Notifier

The code sample at the documentation of EVENTS enqueue and EVENTS dequeue are usage samples of the `finished` event:

```
$notifier->on(finished => sub { my ($notifier, $job_id) = @_; ... });
```

Should be enqueue & dequeue I believe.

**Comment by jberger** [comment]
These were already fixed, I guess I just haven't released since then https://github.com/jberger/Minion-Notifier/commit/6cb1717f84fbac575e2fa736a8c3007ed8223536
